(function(){'use strict';
const state={cms:null};
const $=s=>document.querySelector(s);
const el=(tag,cls,text)=>{const e=document.createElement(tag);if(cls)e.className=cls;if(text!==undefined)e.textContent=text;return e};
const field=(label,name,value,type='text')=>{const w=el('label','block');w.append(el('span','block text-sm font-semibold text-heading mb-1.5',label));const i=document.createElement(type==='textarea'?'textarea':'input');i.name=name;i.value=value??'';if(type==='textarea')i.rows=4;i.className='admin-input';w.append(i);return w};
async function api(mode,opt={}){const r=await fetch('/api/chat?mode='+encodeURIComponent(mode),{cache:'no-store',...opt,headers:{...(opt.headers||{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.error||'Request failed');return b}
function toast(msg,bad=false){const t=el('div','toast',msg);t.style.background=bad?'#a61b1b':'#111';document.body.append(t);setTimeout(()=>t.remove(),3200)}
function login(){document.body.innerHTML='';const shell=el('main','min-h-screen flex items-center justify-center p-6'),card=el('section','material-card p-8 w-full max-w-md');card.append(el('div','text-xs font-bold uppercase tracking-widest text-gold','Private Control Center'),el('h1','font-display text-3xl font-bold text-heading mt-2','Voice-O-Magic Admin'),el('p','text-sec text-sm mt-2','Authorized administrator access only.'));const f=el('form','space-y-5 mt-7'),p=field('Administrator password','password','');p.querySelector('input').type='password';p.querySelector('input').autocomplete='current-password';const err=el('p','text-sm text-red-700');err.hidden=true;const b=el('button','btn-primary w-full','Sign in');f.append(p,err,b);f.addEventListener('submit',async e=>{e.preventDefault();b.disabled=true;b.textContent='Signing in…';try{await api('admin-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:p.querySelector('input').value})});const d=await api('admin-data');state.cms=d.cms;dashboard()}catch(x){err.textContent=x.message;err.hidden=false;b.disabled=false;b.textContent='Sign in'}});card.append(f);shell.append(card);document.body.append(shell)}
function dashboard(){document.body.innerHTML='';const root=el('main','max-w-7xl mx-auto p-5 md:p-8 space-y-6');const head=el('div','flex flex-col md:flex-row justify-between gap-3 items-start md:items-center');head.append(el('div','', 'Voice-O-Magic Control Center'));const actions=el('div','flex gap-2');const save=el('button','btn-primary','Save All Changes'),logout=el('button','btn-secondary','Logout');actions.append(save,logout);head.append(actions);root.append(head);const status=el('div','text-sm text-sec');root.append(status);const settings=el('section','material-card p-6'),video=el('section','material-card p-6');settings.append(el('h2','text-2xl font-bold text-heading mb-5','Page Content'));const s=state.cms.settings;const sg=el('div','grid md:grid-cols-2 gap-4');[['Resources label','resourcesLabel'],['Resources heading','resourcesHeading'],['Resources paragraph','resourcesParagraph','textarea'],['Extra paragraph','resourcesExtraParagraph','textarea'],['Toolkit heading','toolkitHeading'],['Toolkit description','toolkitDescription','textarea'],['Books label','booksLabel'],['Books heading','booksHeading'],['Books paragraph','booksParagraph','textarea']].forEach(x=>sg.append(field(x[0],x[1],s[x[1]],x[2])));const mm=document.createElement('input');mm.type='checkbox';mm.name='maintenanceMode';mm.checked=s.maintenanceMode;sg.append(el('label','flex gap-2 items-center', '').appendChild(mm).parentElement||el('div'));const ml=sg.lastChild;ml.append(el('span','text-sm font-semibold','Maintenance mode'));settings.append(sg);root.append(settings);const v=state.cms.featuredVideo;video.append(el('h2','text-2xl font-bold text-heading mb-5','Featured YouTube Video'));const vg=el('div','grid md:grid-cols-2 gap-4');vg.append(field('YouTube URL','featuredVideoUrl',v.url),field('Video title','featuredVideoTitle',v.title),field('Description','featuredVideoDescription',v.description,'textarea'));const vp=document.createElement('input');vp.type='checkbox';vp.name='featuredVideoPublished';vp.checked=v.published;const vl=el('label','flex gap-2 items-center');vl.append(vp,el('span','text-sm font-semibold','Published'));vg.append(vl);video.append(vg);root.append(video);
const sections={};
function section(title,key,isBook){const sec=el('section','material-card p-6'),list=el('div','space-y-4 mt-4'),add=el('button','btn-secondary mt-4','+ Add '+(isBook?'Book':key==='resources'?'Resource':'Toolkit Item'));add.type='button';add.onclick=()=>{const x={id:crypto.randomUUID(),title:'',description:'',buttonText:isBook?'Learn More':'Download',order:state.cms[key].length,published:true};if(isBook)Object.assign(x,{bookHeading:'',authors:'',categoryLabel:'',coverImageUrl:'',destinationUrl:''});else x.driveUrl='';state.cms[key].push(x);renderLists()};sec.append(el('h2','text-2xl font-bold text-heading',title),list,add);sections[key]={sec,list,isBook};return sec}
root.append(section('Resources','resources',false),section('Speaker Toolkit','toolkit',false),section('Books','books',true));
function renderLists(){Object.entries(sections).forEach(([key,obj])=>{obj.list.replaceChildren();state.cms[key].sort((a,b)=>a.order-b.order).forEach((x,i)=>{const c=el('div','border border-light rounded-xl p-4'),g=el('div','grid md:grid-cols-2 gap-4');g.append(field('Title','title',x.title));if(obj.isBook){g.append(field('Book heading','bookHeading',x.bookHeading),field('Authors','authors',x.authors),field('Category','categoryLabel',x.categoryLabel),field('Description','description',x.description,'textarea'),field('Cover HTTPS URL','coverImageUrl',x.coverImageUrl),field('Destination HTTPS URL','destinationUrl',x.destinationUrl),field('Button text','buttonText',x.buttonText))}else{g.append(field('Description','description',x.description,'textarea'),field('Google Drive / Docs HTTPS URL','driveUrl',x.driveUrl),field('Button text','buttonText',x.buttonText))}g.append(field('Display order','order',x.order));const controls=el('div','flex flex-wrap gap-2 items-center mt-3'),p=document.createElement('input');p.type='checkbox';p.checked=x.published;controls.append(p,el('span','text-sm font-semibold','Published'));const up=el('button','btn-secondary','Up'),down=el('button','btn-secondary','Down'),del=el('button','btn-secondary','Delete');up.type=down.type=del.type='button';up.disabled=i===0;down.disabled=i===state.cms[key].length-1;up.onclick=()=>{const y=state.cms[key][i-1];[x.order,y.order]=[y.order,x.order];renderLists()};down.onclick=()=>{const y=state.cms[key][i+1];[x.order,y.order]=[y.order,x.order];renderLists()};del.onclick=()=>{if(confirm('Delete this item?')){state.cms[key]=state.cms[key].filter(y=>y!==x);renderLists()}};controls.append(up,down,del);c.append(g,controls);c._x=x;c._fields=[...g.querySelectorAll('input,textarea')];c._published=p;obj.list.append(c)})})}
renderLists();save.onclick=async()=>{try{const find=n=>document.querySelector('[name="'+n+'"]');Object.keys(s).filter(k=>k!=='maintenanceMode').forEach(k=>{s[k]=find(k).value});s.maintenanceMode=find('maintenanceMode').checked;state.cms.featuredVideo={url:find('featuredVideoUrl').value,title:find('featuredVideoTitle').value,description:find('featuredVideoDescription').value,published:find('featuredVideoPublished').checked};Object.entries(sections).forEach(([key,obj])=>obj.list.querySelectorAll('[data-x]').forEach(()=>{}));Object.entries(sections).forEach(([key,obj])=>{obj.list.children.forEach(c=>{const x=c._x;c._fields.forEach(i=>{if(i.name==='order')x.order=Number(i.value)||0;else if(i.name in x)x[i.name]=i.value});x.published=c._published.checked})});const d=await api('admin-save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cms:state.cms})});state.cms=d.cms;renderLists();status.textContent='Saved successfully.';toast('Saved successfully.')}catch(x){status.textContent=x.message;toast(x.message,true)}};logout.onclick=async()=>{try{await api('admin-logout',{method:'POST'})}finally{login()}}
const hist=el('section','material-card p-6');hist.append(el('h2','text-2xl font-bold text-heading','Version History'));(state.cms.history||[]).slice().reverse().forEach(v=>{const r=el('div','flex justify-between items-center border border-light rounded-lg p-3 mt-2');r.append(el('span','text-sm text-sec',new Date(v.at).toLocaleString()));const b=el('button','btn-secondary','Restore');b.onclick=async()=>{if(!confirm('Restore this version?'))return;try{const d=await api('admin-restore',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({versionId:v.id})});state.cms=d.cms;dashboard();toast('Version restored.')}catch(x){toast(x.message,true)}};r.append(b);hist.append(r)});root.append(hist);document.body.append(root)}
(async()=>{try{const d=await api('admin-data');state.cms=d.cms;dashboard()}catch{login()}})();
})();
