(function(){'use strict';
const S={cms:null,versions:[],dirty:false};
const el=(t,c,text)=>{const n=document.createElement(t);if(c)n.className=c;if(text!==undefined)n.textContent=text;return n};
const $=(s,r=document)=>r.querySelector(s);
const api=async(mode,opt={})=>{const r=await fetch('/api/chat?mode='+encodeURIComponent(mode),{cache:'no-store',...opt,headers:{...(opt.headers||{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw Error(b.error||'Request failed');return b};
const clone=o=>JSON.parse(JSON.stringify(o));
const uid=()=>globalThis.crypto?.randomUUID?crypto.randomUUID():'item-'+Date.now()+'-'+Math.random().toString(36).slice(2);
function toast(msg,bad=false){const n=el('div','fixed right-5 bottom-5 z-[120] max-w-sm rounded-xl px-4 py-3 text-sm font-semibold text-white shadow-xl',msg);n.style.background=bad?'#b42318':'#111827';document.body.append(n);setTimeout(()=>n.remove(),3200)}
function dirty(){S.dirty=true;const b=$('#saveAll');if(b)b.textContent='Save All Changes • Unsaved'}
function field(label,value,type,fn){const w=el('label','block');w.append(el('span','block text-sm font-semibold mb-1.5 text-sec',label));const i=document.createElement(type==='textarea'?'textarea':'input');i.className='md-input';i.value=String(value??'');if(type==='textarea')i.rows=4;i.addEventListener('input',()=>{fn(i.value);dirty()});w.append(i);return w}
function check(label,value,fn){const w=el('label','inline-flex items-center gap-2 text-sm font-semibold text-sec cursor-pointer'),i=document.createElement('input');i.type='checkbox';i.checked=!!value;i.onchange=()=>{fn(i.checked);dirty()};w.append(i,el('span','',label));return w}
function saveBtn(section){const b=el('button','btn-primary text-sm','Save '+section);b.type='button';b.dataset.section=section;b.onclick=()=>saveSection(section);return b}
function header(title,where,page,section,help){const h=el('div','flex flex-col lg:flex-row lg:justify-between gap-4');const c=el('div');c.append(el('h2','text-xl md:text-2xl font-bold text-heading',title),el('p','text-sm text-muted mt-1','Where: '+where));if(help)c.append(el('p','text-xs text-muted mt-2',help));const a=el('div','flex flex-wrap gap-2');const open=el('a','btn-secondary text-sm','Open page');open.href=page;open.target='_blank';open.rel='noopener noreferrer';a.append(open,saveBtn(section));h.append(c,a);return h}
function meta(k){return{resources:['📄','Resources','Resource','resources.html'],toolkit:['🎤','Speaker Toolkit','Toolkit Item','resources.html'],books:['📚','Books','Book','books.html']}[k]}
function blank(k){const x={id:uid(),title:'',description:'',buttonText:k==='books'?'Learn More':'Download',order:S.cms[k].length,published:true};if(k==='books')Object.assign(x,{bookHeading:'',authors:'',categoryLabel:'',coverImageUrl:'',destinationUrl:''});else x.driveUrl='';return x}
function editItem(k,item){const m=meta(k),o=el('div','fixed inset-0 z-[100] bg-black/50 p-4 md:p-8 overflow-y-auto'),modal=el('section','material-card max-w-3xl mx-auto'),head=el('header','flex items-center justify-between p-5 border-b border-theme');head.append(el('div','font-bold text-heading',m[0]+' '+(item.title||'New '+m[2])));const close=el('button','btn-secondary','Close');close.type='button';close.onclick=()=>o.remove();head.append(close);modal.append(head);const body=el('div','p-5 space-y-4');body.append(field('Title',item.title,'text',v=>item.title=v));if(k==='books')body.append(field('Book heading',item.bookHeading,'text',v=>item.bookHeading=v),field('Author name(s)',item.authors,'text',v=>item.authors=v),field('Category / label',item.categoryLabel,'text',v=>item.categoryLabel=v),field('Description',item.description,'textarea',v=>item.description=v),field('Cover image HTTPS URL',item.coverImageUrl,'text',v=>item.coverImageUrl=v),field('Destination HTTPS URL',item.destinationUrl,'text',v=>item.destinationUrl=v));else body.append(field('Description',item.description,'textarea',v=>item.description=v),field('Google Drive / Docs HTTPS URL',item.driveUrl,'text',v=>item.driveUrl=v));body.append(field('Button text',item.buttonText,'text',v=>item.buttonText=v),field('Display order',item.order,'number',v=>item.order=Number(v)||0),check('Published',item.published,v=>item.published=v));const foot=el('footer','flex justify-end gap-2 p-5 border-t border-theme'),cancel=el('button','btn-secondary','Cancel'),done=el('button','btn-primary','Done');cancel.type=done.type='button';cancel.onclick=()=>o.remove();done.onclick=()=>{o.remove();render()};foot.append(cancel,done);modal.append(body,foot);o.append(modal);o.onclick=e=>{if(e.target===o)o.remove()};document.body.append(o)}
function itemCard(k,item,index){const m=meta(k),card=el('article','material-card p-4'),row=el('div','flex flex-col xl:flex-row xl:items-start justify-between gap-4'),info=el('div','min-w-0');info.append(el('div','font-bold text-lg text-heading break-words',item.title||'Untitled '+m[2]),el('p','text-sm text-sec mt-1',item.description||'No description yet.'),el('span','inline-flex w-fit mt-2 rounded-full px-2.5 py-1 text-xs font-bold '+(item.published?'bg-green-light text-green':'bg-gray-100 text-gray-600'),item.published?'Published':'Hidden'));const actions=el('div','flex flex-wrap gap-2');[['Edit',()=>editItem(k,item)],['Duplicate',()=>{const c=clone(item);c.id=uid();c.title=(c.title||'New '+m[2])+' (Copy)';c.order=S.cms[k].length;S.cms[k].push(c);dirty();render()}],[item.published?'Hide':'Publish',()=>{item.published=!item.published;dirty();render()}],['↑',()=>move(k,index,-1)],['↓',()=>move(k,index,1)],['Delete',()=>{if(!confirm('Delete this item? You can undo by reloading before saving.'))return;S.cms[k]=S.cms[k].filter(x=>x!==item).map((x,i)=>({...x,order:i}));dirty();render()}]].forEach(([label,fn])=>{const b=el('button','btn-secondary text-sm',label);b.type='button';b.disabled=(label==='↑'&&index===0)||(label==='↓'&&index===S.cms[k].length-1);b.onclick=fn;actions.append(b)});row.append(info,actions);card.append(row);return card}
function move(k,i,d){const j=i+d;if(j<0||j>=S.cms[k].length)return;[S.cms[k][i].order,S.cms[k][j].order]=[S.cms[k][j].order,S.cms[k][i].order];dirty();render()}
function collection(root,k){const m=meta(k),box=el('section','material-card p-5');box.append(header(m[0]+' '+m[1],m[1]+' page → '+(k==='toolkit'?'Speaker Toolkit cards':'content cards'),m[3],m[1]));const add=el('button','btn-secondary text-sm mt-4','+ Add '+m[2]);add.type='button';add.onclick=()=>{S.cms[k].push(blank(k));dirty();render()};box.append(add);const list=el('div','space-y-3 mt-4');[...S.cms[k]].sort((a,b)=>a.order-b.order).forEach((x,i)=>list.append(itemCard(k,x,i)));if(!S.cms[k].length)list.append(el('div','rounded-xl border border-dashed border-theme p-8 text-center text-muted','No items yet. Add one above.'));box.append(list);root.append(box)}
function pageCopy(root){const box=el('section','material-card p-5'),s=S.cms.settings;box.append(header('⚙️ Page Copy','Resources + Books pages → introductory copy','resources.html','Page Copy','These fields control the visible copy above the cards.'));const g=el('div','grid md:grid-cols-2 gap-4 mt-5');[['Resources label','resourcesLabel'],['Resources heading','resourcesHeading'],['Resources paragraph','resourcesParagraph','textarea'],['Extra paragraph','resourcesExtraParagraph','textarea'],['Toolkit heading','toolkitHeading'],['Toolkit description','toolkitDescription','textarea'],['Books label','booksLabel'],['Books heading','booksHeading'],['Books paragraph','booksParagraph','textarea']].forEach(([l,k,t])=>g.append(field(l,s[k],t||'text',v=>s[k]=v)));g.append(check('Maintenance mode',s.maintenanceMode,v=>s.maintenanceMode=v));box.append(g);root.append(box)}
function video(root){const box=el('section','material-card p-5'),v=S.cms.featuredVideo;box.append(header('🎬 Featured Video','Resources → featured video block','resources.html','Featured Video','Change the URL, title, description, or visibility of the public video.'));const g=el('div','grid md:grid-cols-2 gap-4 mt-5');g.append(field('YouTube URL',v.url,'text',x=>v.url=x),field('Video title',v.title,'text',x=>v.title=x),field('Description',v.description,'textarea',x=>v.description=x),check('Published',v.published,x=>v.published=x));box.append(g);root.append(box)}
function versions(root){const box=el('section','material-card p-5');box.append(el('h2','text-xl md:text-2xl font-bold text-heading','🕘 Version History'),el('p','text-sm text-muted mt-1','Git-backed versions. Restore only after reviewing the target version.'));S.versions.forEach((v,i)=>{const row=el('div','flex flex-col sm:flex-row justify-between gap-3 rounded-xl border border-theme p-3 mt-3');row.append(el('div','text-sm text-heading',v.at?new Date(v.at).toLocaleString():'Unknown time'));const b=el('button','btn-secondary text-sm',i===0?'Current':'Restore');b.type='button';b.disabled=i===0;b.onclick=async()=>{if(!confirm('Restore this version?'))return;b.disabled=true;b.textContent='Restoring…';try{const r=await api('admin-restore',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({versionId:v.id})});S.cms=r.cms;S.dirty=false;render();toast('Version restored.')}catch(e){b.disabled=false;b.textContent='Restore';toast(e.message,true)}};row.append(b);box.append(row)});if(!S.versions.length)box.append(el('p','text-sm text-muted mt-4','No CMS versions found.'));root.append(box)}
function mergeSection(local,latest,key){const out=clone(latest);if(key==='settings')out.settings={...latest.settings,...local.settings};else out[key]=clone(local[key]);return out}
async function saveSection(section){const b=$(`[data-section="${CSS.escape(section)}"]`);if(b){b.disabled=true;b.textContent='Saving…'}try{const latest=(await api('admin-data')).cms;const key={'Page Copy':'settings','Featured Video':'featuredVideo','Resources':'resources','Speaker Toolkit':'toolkit','Books':'books'}[section];const merged=mergeSection(S.cms,latest,key);const saved=(await api('admin-save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cms:merged})})).cms;S.cms[key]=clone(saved[key]);if(key==='settings')S.cms.settings={...S.cms.settings,...saved.settings};S.dirty=false;toast(section+' saved successfully.')}catch(e){toast(e.message,true)}finally{const x=$(`[data-section="${CSS.escape(section)}"]`);if(x){x.disabled=false;x.textContent='Save '+section}}}
async function saveAll(){const b=$('#saveAll');if(b){b.disabled=true;b.textContent='Saving…'}try{const r=await api('admin-save',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({cms:S.cms})});S.cms=r.cms;S.dirty=false;render();toast('All CMS changes saved successfully.')}catch(e){toast(e.message,true)}finally{const x=$('#saveAll');if(x){x.disabled=false;x.textContent='Save All Changes'}}}
async function load(){const d=await api('admin-data');S.cms=d.cms;S.versions=Array.isArray(d.versions)?d.versions:[]}
function render(){document.body.replaceChildren();const root=el('main','max-w-7xl mx-auto p-4 sm:p-6 md:p-8 space-y-6'),head=el('header','rounded-2xl bg-[#111827] text-white p-5 md:p-6 flex flex-col lg:flex-row justify-between gap-4 items-start lg:items-center');const title=el('div');title.append(el('div','text-xs font-bold uppercase tracking-[0.18em] text-[#d7bd62]','Private Control Center'),el('h1','text-2xl md:text-3xl font-bold mt-1','Voice-O-Magic CMS'),el('p','text-sm text-gray-300 mt-1 max-w-2xl','Edit content by page and exact location. Save one section or everything at once.'));const actions=el('div','flex flex-wrap gap-2'),all=el('button','btn-primary','Save All Changes');all.id='saveAll';all.type='button';all.onclick=saveAll;const logout=el('button','btn-secondary','Logout');logout.type='button';logout.onclick=async()=>{try{await api('admin-logout',{method:'POST'})}finally{S.cms=null;login()}};actions.append(all,logout);head.append(title,actions);root.append(head);const map=el('section','material-card p-5');map.append(el('h2','text-lg font-bold text-heading','🧭 Content map'),el('p','text-sm text-muted mt-1','Every editor shows where its changes appear. Open the public page in a new tab before editing.'));const grid=el('div','grid sm:grid-cols-2 lg:grid-cols-4 gap-3 mt-4');[['Resources','resources.html','Intro · video · resource cards · toolkit'],['Books','books.html','Intro · book cards'],['Featured Video','resources.html','Featured video block'],['Page Copy','resources.html','Resources + Books copy']].forEach(([n,u,d])=>{const a=el('a','rounded-xl border border-theme p-4 hover:border-gold-muted transition');a.href=u;a.target='_blank';a.rel='noopener noreferrer';a.append(el('div','font-bold text-heading',n),el('div','text-xs text-muted mt-1',d));grid.append(a)});map.append(grid);root.append(map);const note=el('div','material-card px-4 py-3 text-sm');note.append(el('strong','text-heading','Safe editing: '),el('span','text-sec','saving one section updates only that section on the server and keeps unrelated unsaved drafts in this browser.'));root.append(note);const c=el('div','space-y-6');pageCopy(c);video(c);collection(c,'resources');collection(c,'toolkit');collection(c,'books');versions(c);root.append(c);document.body.append(root)}
function login(){document.body.replaceChildren();const shell=el('main','min-h-screen flex items-center justify-center p-5 bg-theme'),card=el('section','material-card w-full max-w-md p-7 md:p-8');card.append(el('div','text-xs font-bold uppercase tracking-[0.18em] text-gold','Private Control Center'),el('h1','font-display text-3xl font-bold mt-2 text-heading','Voice-O-Magic Admin'),el('p','text-sm text-sec mt-2','Authorized administrator access only.'));const f=el('form','space-y-4 mt-7'),lab=el('label','block text-sm font-semibold text-sec','Administrator password'),i=document.createElement('input');i.type='password';i.autocomplete='current-password';i.required=true;i.className='md-input mt-1.5';lab.append(i);const err=el('p','text-sm text-red');err.hidden=true;const b=el('button','btn-primary w-full','Sign in');b.type='submit';f.append(lab,err,b);f.onsubmit=async e=>{e.preventDefault();err.hidden=true;b.disabled=true;b.textContent='Signing in…';try{await api('admin-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:i.value})});await load();render()}catch(x){err.textContent=x.message||'Login failed.';err.hidden=false;b.disabled=false;b.textContent='Sign in'}};card.append(f);shell.append(card);document.body.append(shell);i.focus()}
window.addEventListener('beforeunload',e=>{if(S.dirty){e.preventDefault();e.returnValue=''}});
(async()=>{try{await load();render()}catch{login()}})();
})();